### ISSUE TITLE
Add contract which transfers masterchef emissions to reliquary

### ISSUE THREAD

**Issue by 0xSkly** [beethovenxfi/beethovenx-token#25]
We'll have a placeholder pool on the masterchef contract which collects emission for reliquary. We should have a contract implementing ERC20 which is the only one in this pool with a single function to harvest and transfer the emissions to reliquary.

This contract should use the Authenticated open zeppelin contract to protect the harvestAndTransfer function

**Comment by franzns** [comment]
deposit and exit position function

**Comment by franzns** [comment]
merged here https://github.com/beethovenxfi/beethovenx-token/pull/26
tested also on chain, needs deployment once reliquary is up

**Comment by franzns** [comment]
new version that sets emissions/s

**Comment by franzns** [comment]
adjusted the bot that will run the whole thing as well
